{% set name = "easycheck" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/easycheck-{{ version }}.tar.gz
  sha256: b77bdcafc0d1183215abb610fac17cc82937c678fc9a3c7b00e012cabb82c7f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - easycheck
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nyggus/easycheck
  summary: A tool for simple functionalized assertions in Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
