{% set name = "easycheck" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/easycheck-{{ version }}.tar.gz
  sha256: 8a937ad07420a8fd34dd402a98a23d7e83fbf881af959d11d07c20f4813a0e10

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - easycheck
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nyggus/easycheck
  summary: A tool for simple functionalized assertions in Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
